db:
  server: wits-sql-server.database.windows.net
  database: wits

llm:
  endpoint: https://wits-ai.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2024-08-01-preview
  model: gpt-4
  api_version: 2024-02-15-preview